version: "3"

services:
  trino-coordinator:
    image: 'trinodb/trino:latest'
    hostname: trino-coordinator
    ports:
      - '8080:8080'
    volumes:
      - ../trino/etc:/etc/trino
volumes:
  hive-metastore-postgresql:

networks:
  default:
    name: hudi
